KS-2-4 add solving for task 2-4
curiose/KotlinSprints pull request #9
Opened 2024-07-13 20:27 UTC by curiose

2024-07-13 22:09 UTC, ievetrovdev requested changes

2024-07-13 22:09 UTC, ievetrovdev commented on src/main/kotlin/lesson_2_4.kt
> +const val BUFF = 0.20
Для возможности гибкой работы с кодом, следует инициализировать согласно ТЗ проценты целым числом 20. И уже потом производить вычисление процентов. Таким образом, если нужен будет другой процент, достаточно будет поменять значение в одном месте.

2024-07-15 16:39 UTC, curiose commented on src/main/kotlin/lesson_2_4.kt
> +const val BUFF = 0.20
Я не уверена, что верно поняла, то перенесла переменную с процентом в обычную переменную val, если она может меняться

2024-07-15 17:34 UTC, ievetrovdev requested changes

2024-07-15 17:34 UTC, ievetrovdev commented on src/main/kotlin/lesson_2_4.kt
> +    val crystalOreWithBuff = (crystalOre * buff) / 100.toInt()
Все верно, кроме того что 100 теперь магическое число, давай вынесем в константу

2024-07-16 10:30 UTC, ievetrovdev approved these changes
Отличное решение, все верно!

2024-07-16 10:52 UTC, merged